### PR TITLE
fix code of spanish bible

### PR DESCRIPTION
**Pull request by joejoe2016**

### CODE REVIEW

**Comment by chrislim** [comment]
Do you want to add an es_ES and es_MX locale for the Spanish bibles? I think that may enable a default Bible to be selected for phones in those locales.

**Comment by joejoe2016** [comment]
Hi,
Yes I could add es_ES and es_MX. But I wonder what will then happen on cel phones in eg Argentina which uses es_AR. Will they then see English bible translations?

**Comment by chrislim** [comment]
We could change this file: https://github.com/ceaseless-prayer/ceaseless-api-lambda/blob/master/utils/getLanguage.js

So that it extracts the language prefix. That way all es_* locales could lookup the es key.

**Comment by chrislim** [comment]
FYI, I merged the PR and added the commit ffde8d48 to support using "es" as the key.

**Comment by joejoe2016** [comment]
Hi,
Coll, I was about to suggest the same thing but you were faster. ;-)

Although when I set the bible to spanish in the settings of the android app (I made a local build) to spanish I still get the bible verse in english when reloading the verse. I'll have to debug into it to see what's going wrong.

**Comment by chrislim** [comment]
Hmm, ok, the lambda should be deployed, but if we need better insight, I could log the locales going to it and we could see which locale your phone is sending.

**Pull request merged**
